# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder ".", "/home/vagrant/code"

  config.vm.provision :shell, path: "./bootstrap.sh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

end
